version: "3"

services: 
  app:
    image: gausia7/mynodeapp
    ports: 
      - 3000:3000

    depends_on: 
      - mysql-server
  
  mysql-server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

    